version: "3.8"

services:
  frontend:
    build: ./FRONTEND
    container_name: frontend
    expose:
      - "3000"
    env_file:
      - ./FRONTEND/.env
    depends_on:
      - api

  crm:
    build: ./CRM
    container_name: crm
    expose:
      - "3000"
    env_file:
      - ./CRM/.env
    depends_on:
      - api

  api:
    build: ./API
    container_name: api
    expose:
      - "3000"
    env_file:
      - ./API/.env
    depends_on:
      - db

  upload:
    build: ./API_UPLOAD
    container_name: upload
    expose:
      - "3000"
    env_file:
      - ./API_UPLOAD/.env
    volumes:
      - ./uploaded-files/uploads:/app/uploads
      - ./uploaded-files/private:/app/private
    depends_on:
      - db

  db:
    image: postgres:17.4
    container_name: postgres
    environment:
      POSTGRES_DB: trek_sikkim
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: trek123
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  mailserver:
    image: docker.io/mailserver/docker-mailserver:latest
    container_name: mailserver
    hostname: mail
    domainname: trekinsikkim.in
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "993:993"
    volumes:
      - ./mailserver/data:/var/mail
      - ./mailserver/state:/var/mail-state
      - ./mailserver/logs:/var/log/mail
      - ./mailserver/config:/tmp/docker-mailserver
      - ./nginx/letsencrypt:/etc/letsencrypt
    environment:
      - SSL_TYPE=letsencrypt
      - SSL_DOMAIN=trekinsikkim.in
      - ENABLE_SPAMASSASSIN=1
      - ENABLE_CLAMAV=1
      - ENABLE_FAIL2BAN=1
      - ONE_DIR=1
      - PERMIT_DOCKER=connected-networks
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
    restart: always

  webmail:
    image: roundcube/roundcubemail:latest
    container_name: roundcube
    environment:
      - ROUNDCUBEMAIL_DEFAULT_HOST=mailserver
      - ROUNDCUBEMAIL_SMTP_SERVER=mailserver
      - ROUNDCUBEMAIL_SMTP_PORT=587
      - ROUNDCUBEMAIL_DEFAULT_PORT=993
    volumes:
      - ./webmail:/var/www/html
    depends_on:
      - mailserver
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - frontend
      - crm
      - api
      - upload
      - webmail
    restart: always

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: [
      "certbot", "certonly", "--webroot",
      "--webroot-path=/var/www/certbot",
      "--force-renewal",
      "--email", "treksikkim.ommdigitalsoluction@gmail.com",
      "--agree-tos",
      "--no-eff-email",
      "-d", "trekinsikkim.in",
      "-d", "www.trekinsikkim.in",
      "-d", "crm.trekinsikkim.in",
      "-d", "api.trekinsikkim.in",
      "-d", "upload.trekinsikkim.in",
      "-d", "mail.trekinsikkim.in"
    ]
    depends_on:
      - nginx

volumes:
  db_data: