version: "3.8"

services:
  frontend:
    build: ./FRONTEND
    container_name: frontend
    expose:
      - "3000"
    env_file:
      - ./FRONTEND/.env
    depends_on:
      - api

  crm:
    build: ./CRM
    container_name: crm
    expose:
      - "3000"
    env_file:
      - ./CRM/.env
    depends_on:
      - api

  api:
    build: ./API
    container_name: api
    expose:
      - "3000"
    env_file:
      - ./API/.env
    depends_on:
      - db

  upload:
    build: ./API_UPLOAD
    container_name: upload
    expose:
      - "3000"
    env_file:
      - ./API_UPLOAD/.env
    volumes:
      - ./uploaded-files/uploads:/app/uploads
      - ./uploaded-files/private:/app/private
    depends_on:
      - db

  db:
    image: postgres:17.4
    container_name: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    container_name: mailserver
    hostname: mail.trekinsikkim.in
    ports:
      - "25:25" # SMTP
      - "143:143" # IMAP
      - "587:587" # SMTP submission
      - "993:993" # IMAPS
    volumes:
      - ./docker-data/dms/mail-data/:/var/mail/
      - ./docker-data/dms/mail-state/:/var/mail-state/
      - ./docker-data/dms/mail-logs/:/var/log/mail/
      - ./docker-data/dms/config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
    environment:
      - ENABLE_SPAMASSASSIN=1
      - ENABLE_CLAMAV=1
      - ENABLE_FAIL2BAN=1
      - ENABLE_POSTGREY=1
      - ONE_DIR=1
      - DMS_DEBUG=0
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
    restart: always

  # Webmail interface
  roundcube:
    image: roundcube/roundcubemail:latest
    container_name: roundcube
    expose:
      - "80"
    depends_on:
      - mailserver
    environment:
      - ROUNDCUBEMAIL_DEFAULT_HOST=mailserver
      - ROUNDCUBEMAIL_SMTP_SERVER=mailserver
      - ROUNDCUBEMAIL_SMTP_PORT=587
    restart: always

  wordpress:
    image: wordpress:latest
    container_name: wordpress
    restart: always
    depends_on:
      - mysql
    expose:
      - "80"
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX}
    volumes:
      - wordpress_data:/var/www/html
      - ./custom.conf:/etc/apache2/sites-available/000-default.conf

  mysql:
    image: mysql:5.7
    restart: always
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - frontend
      - crm
      - api
      - upload
      # - webmail
    restart: always

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint:
      [
        "certbot",
        "certonly",
        "--webroot",
        "--webroot-path=/var/www/certbot",
        "--force-renewal",
        "--email",
        "treksikkim.ommdigitalsoluction@gmail.com",
        "--agree-tos",
        "--no-eff-email",
        "-d",
        "trekinsikkim.in",
        "-d",
        "www.trekinsikkim.in",
        "-d",
        "crm.trekinsikkim.in",
        "-d",
        "api.trekinsikkim.in",
        "-d",
        "upload.trekinsikkim.in",
        "-d",
        "mail.trekinsikkim.in",
        "-d",
        "blog.trekinsikkim.in",
      ]
    depends_on:
      - nginx

volumes:
  db_data:
  mysql_data:
  wordpress_data:
