import type { Metadata } from "next";
import { Poppins, Montserrat } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import Constant from "@/constant";
import BottomNavigation from "@/components/BottomNavigation";
import ReduxProvider from "@/redux/ReduxProvider";
import ScrollProgress from "@/components/ScrollProgress";
import HeaderHolder from "@/components/HeaderHolder";
import FooterHolder from "@/components/FooterHolder";
import DialogWrapper from "@/components/Dialogs/DialogWrapper";
import EnquireDialog from "@/components/Dialogs/EnquireDialog";
import AuthProvider from "@/components/AuthProvider";
import Link from "next/link";
import { ArrowUp } from "lucide-react";
import AiHeader from "@/components/AiComponents/AiHeader";
import ChildrenHolder from "@/components/ChildrenHolder";
import { cn } from "@/lib/utils";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700"], // Regular, Medium, Semi-Bold, Bold
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"], // Regular, Medium, Semi-Bold, Bold
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <div id="top-layout" className="bg-amber-300"></div>
      <body
        className={cn(
          poppins.variable,
          montserrat.variable,
          "antialiased !overflow-y-visible"
        )}
      >
        <ScrollProgress />
        <Constant />
        <Link
          href={"#top-layout"}
          className="size-9 flex items-center justify-center rounded-full fixed z-30 bg-accent right-4 bottom-4"
        >
          <ArrowUp size={18} color="#fff" />
        </Link>
        <AuthProvider>
          <ReduxProvider>
            <DialogWrapper
              id="enquiry-form"
              className="flex justify-center items-start"
            >
              <EnquireDialog />
            </DialogWrapper>
            {/* <HeaderHolder> */}
            <HeaderHolder>
              {/* <Header /> */}
              {/* <NewHeader /> */}
              <AiHeader />
            </HeaderHolder>
            {/* </HeaderHolder> */}
            {/* <ReactLenis root>{children}</ReactLenis> */}
            <BottomNavigation />
            <ChildrenHolder>{children}</ChildrenHolder>
            <FooterHolder>
              <Footer />
            </FooterHolder>
          </ReduxProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
